# Generated by Django 5.2.1 on 2025-05-15 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('statut', models.CharField(choices=[('initialiser', 'Initialisé'), ('en_cours', 'En Cours'), ('termine', 'Terminé')], max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Intervention',
                'verbose_name_plural': 'Interventions',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='InterventionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modification', models.DateTimeField(auto_now_add=True)),
                ('modifications', models.JSONField()),
            ],
            options={
                'verbose_name': "Historique d'intervention",
                'ordering': ['-date_modification'],
            },
        ),
    ]
