# Generated by Django 5.2.1 on 2025-05-15 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicienAdresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ligne1', models.CharField(max_length=255)),
                ('ligne2', models.CharField(blank=True, max_length=255)),
                ('code_postal', models.CharField(max_length=10)),
                ('ville', models.CharField(max_length=100)),
                ('pays', models.CharField(default="Côte d'Ivoire", max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClientAdresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ligne1', models.CharField(max_length=255)),
                ('ligne2', models.CharField(blank=True, max_length=255)),
                ('code_postal', models.CharField(max_length=10)),
                ('ville', models.CharField(max_length=100)),
                ('pays', models.CharField(default="Côte d'Ivoire", max_length=100)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adresses_client', to='clients.client')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
