# Generated by Django 5.2.1 on 2025-05-15 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interventions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RapportIntervention',
            fields=[
                ('intervention', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='rapport', serialize=False, to='interventions.intervention')),
                ('contenu', models.TextField()),
                ('notes_techniques', models.TextField(blank=True)),
                ('feedback_client', models.TextField(blank=True)),
                ('signature_technicien', models.BooleanField(default=False)),
                ('signature_client', models.BooleanField(default=False)),
                ('date_signature_technicien', models.DateTimeField(blank=True, null=True)),
                ('date_signature_client', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': "Rapport d'intervention",
                'verbose_name_plural': "Rapports d'intervention",
            },
        ),
    ]
